# Generated by Django 3.1 on 2020-09-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(blank=True, max_length=150, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('github', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('slug', models.SlugField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [-0.1275, 51.50722]}, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('Picnic Bench', 'Picnic Bench'), ('Park Bench', 'Park Bench'), ('Picnicspot', 'Picnicspot'), ('Picnic Area', 'Picnic Area')], max_length=30, null=True)),
                ('condition', models.CharField(choices=[('Spiffing', 'Spiffing'), ('Okay', 'Okay'), ('Apalling', 'Appalling'), ('Not There', 'Not There')], max_length=30, null=True)),
                ('capacity', models.CharField(choices=[('1-2', '1-2'), ('3-5', '3-5'), ('6-10', '6-10'), ('10+', '10+')], max_length=30, null=True)),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
