# Generated by Django 3.1 on 2020-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bench',
            name='location',
        ),
        migrations.AlterField(
            model_name='bench',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
