# Generated by Django 3.1 on 2020-09-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_bench_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bench',
            options={'ordering': ['date_created']},
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('bench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.bench')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
