# Generated by Django 3.1 on 2020-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200901_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
