# Generated by Django 3.1 on 2020-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200901_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='condition',
            field=models.CharField(choices=[('Spiffing', 'Spiffing'), ('Okay', 'Okay'), ('Apalling', 'Appalling'), ('Not There', 'Not There')], max_length=30, null=True),
        ),
    ]
