# Generated by Django 3.1 on 2020-09-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200906_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bench',
            name='tag',
        ),
    ]
