# Generated by Django 3.1 on 2020-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_usercomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
